---
title: "Lecture 1.3"
format: html
editor: visual
date: 2024-01-08
---

```{r}
library(tidyverse)
```

## Tidy Data

```{r}
# untidy data ----
temp_data_wide <- tribble(
  ~date, ~station1, ~station2,  ~station3,
  "2023-10-01", 30.1, 29.8,  31.2,
  "2023-11-01", 28.6, 29.1,  33.4,
  "2023-12-01", 29.9, 28.5,  32.3
)

# make tidy ---
temp_data_long <- temp_data_wide %>% 
  pivot_longer(col = starts_with('station'),
               names_to = 'station_id',
               values_to = 'temp_c')
```

## plot 1

```{r}
#mapping color globally
ggplot(data = na.omit(penguins), aes(x = bill_length_mm,
                            y = bill_depth_mm,
                            color = species)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  scale_color_manual(values = c('darkorange', 'purple', 'cyan4'))

#mapping color locally
ggplot(data = na.omit(penguins), aes(x = bill_length_mm,
                            y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  geom_smooth(method = 'lm')

```

```{r}
###pipping into a ggplot --- ##
# penguins %>% 
#   ggplot(aes(x = bill_length_mm,
#              y = bill_depth_mm))

####this is for when we want to make individual different mapping with different datasets
# ggplot() +
#   geom_point(data = penguins,
#              mapping = aes(x = bill_length_mm,
#                  y = bill_depth_mm)
#                  
             
ggplot(penguins, aes(x = body_mass_g,
                     y = flipper_length_mm,
                     color = body_mass_g)) +
  geom_point() +
  scale_color_gradient(low = '#123b43', high = '#f7dd4c')
```

## plot 2

```{r}

ggplot(penguins, aes(x = species)) +
  geom_bar()
```

overriding geom_bar()'s stats
```{r}
penguins_summary <- penguins %>% 
  count(species)


ggplot(penguins_summary, aes(x = species, y = n)) +
  geom_bar(stat = 'identity')
```
overriding defaut stat mapping
```{r}

ggplot(penguins, aes(x = species, y = after_stat(prop),
                     group = 1)) +
  geom_bar()

```

position adjustments
```{r}

ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = position_dodge2(preserve = 'single')) #different position includes dodge, fill, stack

# ex postion = 'dodge'

```

coordinate systems + themes
```{r}

ggplot(penguins, aes(x = species)) +
  geom_bar() +
  coord_cartesian() + # coord_cartesian() #coord_polar()+
  theme_classic()+
  theme(axis.title = element_text(size = 17, color = 'purple'))
```


